### ISSUE TITLE
error in step 15

### ISSUE THREAD

**Issue by mortein79** [meeuw/mysql-workbench-fedora-21#1]
Hi!

I trying your method, and error result in step 15

ERROR: Cannot find/open srpm: ../mysql-workbench-community-6.2.4-1.fc21.src.rpm. Error: [Errno 2] No such file or directory: '../mysql-workbench-community-6.2.4-1.fc21.src.rpm'

pwd: ~/rpmbuild . What's the problem? :)

Thank you!

**Comment by meeuw** [comment]
Whoops, I've accidentally kept ../ which should be ~/rpmbuild/SRPMS/

Please retry :-)

**Comment by mortein79** [comment]
Thank you. Almost done...
`Error: Package: mysql-workbench-community-6.2.4-1.fc21.x86_64 (/mysql-workbench-community-6.2.4-1.fc21.x86_64)
           Requires: libantlr3c_wb.so()(64bit)`
:)

**Comment by Rivsen** [comment]
Can't find where libantlr3c_wb.so is when install mysql-workbench-community-6.2.4-1.fc21.x86_64.rpm, same as @mortein79 ...

**Comment by meeuw** [comment]
Thanks for reminding me, I've updated mysql-workbench.spec to ignore this dependency.

Please restart at step 10 (copy mysql-workbench.spec from this repository to ~/rpmbuild/SPEC)

**Comment by mortein79** [comment]
Thank you! Work like a  charm!
