### ISSUE TITLE
Multiple errors with instructions and fails to compile RPM

### ISSUE THREAD

**Issue by taz77** [meeuw/mysql-workbench-fedora-21#2]
There are a lot of problems in the instructions. I just attempted to get this working for the last two hours with no success. I get the C++ connector portion done fine but nothing works after that.  I believe there are several steps you have left out in regards to what directory you should be in and a missing step or a typo with the workbench portion.

The first step that fails is

<blockquote>
mock mysql-connector-c++-1.1.5-1.fc21.src.rpm
</blockquote>

There should be a step before this to cd ~/rpmbuild/SRPMS

Next step that fails is:

<blockquote>mock -r fedora-21-x86_64 --no-clean ../mysql-workbench-community-6.2.4-1.fc21.src.rpm --define 'release 1'</blockquote>

There is no file mysql-workbench-community-6.2.4-1.fc21.src.rpm located one directory up from ~/rpmbuilds/SRPMS being that we had to switch to this directory to complete the steps proceeding it. This has stopped my progress and attempting to work around it hasn't worked either.

Last thing that I noticed immediately is you don't mention the dependency for the Ctemplate 2.2. You cannot compile workbench without 2.2. You must compile Ctemplate it from source since Fedora 21 has ctemplate 3.0. Can be downloaded here: https://code.google.com/p/ctemplate/downloads/list

**Comment by meeuw** [comment]
Hi taz77 sorry to hear the instructions aren't sufficient. Yesterday I've updated readme.txt, it seems you are using the old. 

As you might have found I've added a sed expression to fix fhe ctemplate issue in mysql. 

Please send me the errors you get so I can have a look!

**Comment by meeuw** [comment]
Hi taz77 sorry to hear the instructions aren't sufficient. Yesterday I've updated readme.txt, and I forgot to commit the changes :-(

As you might have found I've added a sed expression to fix fhe ctemplate issue in mysql. 

Please send me the errors you get so I can have a look!

**Comment by taz77** [comment]
Ah that's a huge help! I'll give it a shot now.

**Comment by taz77** [comment]
Found a typo

<blockquote>
copy mysql-workbench.spec from this repository to ~/rpmbuild/SPEC
</blockquote>

should be

copy mysql-workbench.spec from this repository to ~/rpmbuild/SPECS

**Comment by taz77** [comment]
Just got this error:

taz77@tux:~/rpmbuild$ rpmbuild -bs ~/rpmbuild/SPECS/mysql-workbench.spec --define 'release 1'
error: File /home/taz77/rpmbuild/SOURCES/mysql-workbench-community-6.2.4-src.tar.gz: No such file or directory

I downloaded the -src.tar.gz and put it into ~/rpmbuild/SOURCES

Probably should change out the download of mysql-workbench-community-6.2.4-1.fc20.src.rpm to just downloading the source like you did for the C++ connector because the fc20.src.rpm will not install because it depends on Ctemplate 2.2 which is not available in FC21.

**Comment by taz77** [comment]
Got a successful build of RPMs. But this built a fc21.src.rpm? And I cannot do anything with it.

Gives me this:

<blockquote>
Examining mysql-workbench-community-6.2.4-1.fc21.src.rpm: mysql-workbench-community-6.2.4-1.fc21.src
Cannot add package mysql-workbench-community-6.2.4-1.fc21.src.rpm to transaction. Not a compatible architecture: src
</blockquote>

**Comment by meeuw** [comment]
hmm, you should have mysql-workbench-community-6.2.4-1.fc21.x86_64.rpm in /var/lib/mock/fedora-21-x86_64/result/ and you should be able to yum localinstall it... (don't forget to add mysql-connector as well)

**Comment by taz77** [comment]
Yeah it's there. Let me try a local install with it.

**Comment by meeuw** [comment]
I've updated mysql-workbench.spec to ignore the antlr dependency.

Please restart at step 10 (copy mysql-workbench.spec from this repository to ~/rpmbuild/SPEC)

**Comment by remoteclient** [comment]
I get the following error:

``` bash
Fehler: Paket: mysql-workbench-community-6.2.4-1.fc21.x86_64 (/mysql-workbench-community-6.2.4-1.fc21.x86_64)
            Benötigt: libmysqlcppconn.so.7()(64bit)
 Sie können versuchen, mit --skip-broken das Problem zu umgehen.
 Sie könnten Folgendes versuchen: rpm -Va --nofiles --nodigest
```

So YUM didn't find the library which is in /usr/lib64/mysql-workbench. Are there any ideas on how to solve this issue?

**Comment by meeuw** [comment]
@remoteclient easy :-) install mysql-connector-c++-1.1.5-1.fc21.x86_64.rpm together or before installing mysql-workbench-community-6.2.4-1.fc21.x86_64.rpm

**Comment by remoteclient** [comment]
@meeuw Thank you for your fast reply. Your answer worked perfectly.
The only remaining issue now is mysql-workbench and the gnome-keyring. There is a console message: 

``` bash
Message: Gnome keyring daemon seems to not be available. Stored passwords will be lost once quit
Ready.
```

You will be my personal hero if you have a solution on this one too. :)

Edit: It seems I found a solution on myself.
I added

``` bash
export GNOME_KEYRING_CONTROL=1
```

 to the top of /usr/bin/mysql-workbench

**Comment by taz77** [comment]
I'll be honest. I have not been able to do any testing. I compiled workbench from source to where it works and I have been working on clients projects every since.

**Comment by ghost** [comment]
Hi,
Thanks a lot for your good work. However, I faced a problem in the last step.
I also attached the log file with errors.
The error is : 

CMake Error at build/cmake/Modules/FindMySQL.cmake:39 (MESSAGE):
  Cannot find /builddir/mysql-server/bin/mysql_config (MYSQL_CONFIG_PATH)
Call Stack (most recent call first):
  CMakeLists.txt:72 (find_package)

I appreciate your support to help me to resolve this problem.

**Comment by bavodaniels** [comment]
ehsansadr did you manage to fix your issue because i have the same now

**Comment by ghost** [comment]
Hi,
I found another article that may help you. But I haven't gone through it yet.

http://superuser.com/questions/863315/compiling-mysql-workbench-on-fedora-21/
