### ISSUE TITLE
CMake Error at build/cmake/Modules/FindMySQL.cmake:39

### ISSUE THREAD

**Issue by hitzhangjie** [meeuw/mysql-workbench-fedora-21#5]
Hi, I tried to build mysql workbench as you have mentioned, but when I exec the last step, it failed:

 run command:
         mock -r fedora-21-x86_64 --no-clean ~/rpmbuild/SRPMS/mysql-workbench-community-6.2.4-1.fc21.src.rpm --define 'release 1'

error message is:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found GTK2_GTK: /usr/lib64/libgtk-x11-2.0.so  
-- Found GTK2_GTKMM: /usr/lib64/libgtkmm-2.4.so  
-- checking for module 'gthread-2.0'
--   found gthread-2.0, version 2.42.1
-- checking for module 'gmodule-2.0'
--   found gmodule-2.0, version 2.42.1
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.42.1
-- Found SWIG: /usr/lib64/ccache/swig (found version "3.0.5") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.8", minimum required is "2.6") 
CMake Error at build/cmake/Modules/FindMySQL.cmake:39 (MESSAGE):
  Cannot find /builddir/mysql-server/bin/mysql_config (MYSQL_CONFIG_PATH)
Call Stack (most recent call first):
  CMakeLists.txt:72 (find_package)

what should I do to solve this problem?

**Comment by hitzhangjie** [comment]
Do I need to modify the *spec file to configure the mysql_home variable?

**Comment by meeuw** [comment]
Nope this shouldn't be necessary, please try to restart from step mock --clean or download the rpms from the fork https://github.com/cybercog/mysql-workbench-fedora-21

**Comment by hitzhangjie** [comment]
Thank you, meeuw. I installed from https://github.com/cybercog/mysql-workbench-fedora-21. It works!

**Comment by meeuw** [comment]
I've added the rpms to this repository as well

**Comment by ElCoyote27** [comment]
I was having the same issue trying to rebuild on FC23.
I worked around the issue by doing this in my HOME:
$ ln -s /usr mysql-server

Now I'm getting this:
-- Found TINYXML: /usr/lib64/libtinyxml.so  
-- Found GDAL: /export/home/vcojot/linux-res/builds/gdal-gpl/usr/local/lib/libgdal.so  
CMake Error at build/cmake/Modules/FindIODBC.cmake:22 (MESSAGE):
  iodbc-config not found in
  /export/home/vcojot/linux-res/builds/odbc/usr/local/bin/iodbc-config
Call Stack (most recent call first):
  CMakeLists.txt:130 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by ElCoyote27** [comment]
For the latter, I used the same kind of workaround:
mkdir -p linux-res/builds/odbc/usr
cd linux-res/builds/odbc/usr
ln -s /usr local
