### ISSUE TITLE
Would you provided your built rpm package for us to download it directly?

### ISSUE THREAD

**Issue by ghost** [meeuw/mysql-workbench-fedora-21#6]
Would you provided your built rpm package for us to download it directly?

**Comment by meeuw** [comment]
Well actually I thought it would be better if Oracle adapt my patches and publish the RPMs, but I don't think this will happen any time soon. I've added the i686 and x86_64 rpms.

**Comment by ghost** [comment]
Thanks, no more needed, they released new version. provide native rpm package for Fedora 21
